export const CHANGE_INIT_VALUE = 'CHANGE_INIT_VALUE';
export const CHANGE_DEST_VALUE = 'CHANGE_DEST_VALUE';
export const CHANGE_INIT_CURR = 'CHANGE_INIT_CURR';
export const CHANGE_DEST_CURR = 'CHANGE_DEST_CURR';
export const CHANGE_RATE = 'CHANGE_RATE';
